apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-smtp
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ghc-ss-<TENANT_HASH>-vaultwarden
  target:
    name: vaultwarden-smtp
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: tenants/<TENANT_HASH>/app/default/vaultwarden/smtp
        property: username
    - secretKey: password
      remoteRef:
        key: tenants/<TENANT_HASH>/app/default/vaultwarden/smtp
        property: password
