apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
spec:
  instances: 1
  seccompProfile:
    type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 26
    runAsGroup: 26
    fsGroup: 26
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-db
  storage:
    size: 10Gi
    storageClass: hcloud-volumes
