apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghc-example-app-data
  labels:
    app.kubernetes.io/name: ghc-example-app
    app.kubernetes.io/part-of: gh0stcloud-onboarding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
