apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghc-nsp-replace-me-app

resources:
  - ../ghc-advanced

labels:
  - pairs:
      gh0stservice.io/onboarding-track: professional

patches:
  - path: patch-deployment-resources.yaml
