apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <APP_NAME>-secret
  namespace: ghc-nsp-<TENANT_HASH>-<APP_NAME>
spec:
  secretStoreRef:
    name: ghc-ss-<TENANT_HASH>-<APP_NAME>
  data:
    - secretKey: SECRET_KEY_EXAMPLE
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/secret_name
        property: SECRET_KEY_EXAMPLE
    - secretKey: API_KEY_EXAMPLE
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/secret_name
        property: API_KEY_EXAMPLE
    - secretKey: LLM_API_KEY_EXAMPLE
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/secret_name
        property: LLM_API_KEY_EXAMPLE
