apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <APP_NAME>-registry
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ghc-ss-<TENANT_HASH>-<APP_NAME>
  target:
    name: <APP_NAME>-registry
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"{{ .REGISTRY }}":{"username":"{{ .USERNAME }}","password":"{{ .PASSWORD }}","auth":"{{ printf `%s:%s` .USERNAME .PASSWORD | b64enc }}"}}}
  data:
    - secretKey: REGISTRY
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/registry
        property: registry
    - secretKey: USERNAME
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/registry
        property: username
    - secretKey: PASSWORD
      remoteRef:
        key: tenants/<TENANT_HASH>/app/<PROJECT_NAME>/<APP_NAME>/registry
        property: password
